// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuYeSBnWBBWXuSnRFauMu0P7JNrQxYX84',
    appId: '1:719417157029:web:1e8a3371e5a87407cd744c',
    messagingSenderId: '719417157029',
    projectId: 'flutter-mynote-2pos2',
    authDomain: 'flutter-mynote-2pos2.firebaseapp.com',
    storageBucket: 'flutter-mynote-2pos2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbB4AJfpIGM7aERVtdJxH2G6_7vAMLtUU',
    appId: '1:719417157029:android:3036c0c90743080bcd744c',
    messagingSenderId: '719417157029',
    projectId: 'flutter-mynote-2pos2',
    storageBucket: 'flutter-mynote-2pos2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOt4-GNgFedYepNF5BkUteLge74kua8_0',
    appId: '1:719417157029:ios:4c33067760fccb31cd744c',
    messagingSenderId: '719417157029',
    projectId: 'flutter-mynote-2pos2',
    storageBucket: 'flutter-mynote-2pos2.appspot.com',
    iosClientId: '719417157029-b3akml0g6l59tsnsr1c6a2dihsj30n0n.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOt4-GNgFedYepNF5BkUteLge74kua8_0',
    appId: '1:719417157029:ios:4c33067760fccb31cd744c',
    messagingSenderId: '719417157029',
    projectId: 'flutter-mynote-2pos2',
    storageBucket: 'flutter-mynote-2pos2.appspot.com',
    iosClientId: '719417157029-b3akml0g6l59tsnsr1c6a2dihsj30n0n.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
